### ISSUE TITLE
大佬，可否加上微信拍摄的照片、视频时间戳识别

### ISSUE THREAD

**Issue by dreamdesky** [Cryolitia/PhotoTimeFix#3]
最近在整理照片，比较头疼修改时间错乱的问题，一通搜索后找到了大佬开发的这款软件，很好用，先谢谢大佬~

手机自带相机拍摄的照片都能修复，但微信拍摄的无法识别（毫秒时间戳，下面列出来两个常见的文件名）

mmexport1661090654329.jpg
wx_camera_1505788478724.jpg

没学过 C# 所以无法贡献代码，希望大佬能完善下，愿给大佬买杯咖啡

**Comment by Cryolitia** [comment]
@dreamdesky 照片时间修复近期在重构，新写的PC版是支持了这种时间戳的识别的，Android版的重构还在漫长的计划中

**Comment by dreamdesky** [comment]
感谢大佬，我用的就是 PC 版，期待ing

**Comment by Cryolitia** [comment]
@dreamdesky 怪了 我没发布吗，你用不用TG
