### ISSUE TITLE
能不能导出运行日志

### ISSUE THREAD

**Issue by luhua2018** [Cryolitia/PhotoTimeFix#4]
大佬，这东西能不能把运行日志导出来啊，方便文件量很大的时候能筛选哪些成功那些失败了？

![image](https://github.com/Cryolitia/PhotoTimeFix/assets/26620547/0106919f-96b5-44eb-9480-d10c2577ceb5)

**Comment by Cryolitia** [comment]
@luhua2018 有道理 等我出院了写一下

**Comment by luhua2018** [comment]
不急😂，您好好好休息。

**Comment by Cryolitia** [comment]
done in https://github.com/Cryolitia/PhotoTimeFix/commit/533981e73e58ef445acfb6049f476fac5fc36dd8

**Comment by Cryolitia** [comment]
https://github.com/Cryolitia/PhotoTimeFix/commit/67fbb86a32d6a6cd00f1938abd2a1f07063d8216

导出csv格式日志文件
