### ISSUE TITLE
能否修改/添加“创建媒体日期”、“拍摄日期”

### ISSUE THREAD

**Issue by henji-henji** [Cryolitia/PhotoTimeFix#5]
首先感谢您的这个软件，真的太棒了！我正好需要一个按照文件名修改时间属性的软件！
我有两个小小的建议，希望您可以考虑一下：

### 1、对于视频文件，希望能修改“创建媒体日期”
也就是右击“属性”中看到的这个，如果文件本身没有这个属性，就自动添加
在用这款软件之前，我是用 exiftool 来修改的，exiftool 中对应的参数应该是
`-api "QuickTimeUTC" "-MediaCreateDate`
为了保险起见，我还修改了这几个属性
```
-api "QuickTimeUTC" "-TrackCreateDate
-api "QuickTimeUTC" "-TrackModifyDate
-api "QuickTimeUTC" "-MediaModifyDate
```
![创建媒体日期](https://github.com/Cryolitia/PhotoTimeFix/assets/84775360/f5eda370-fded-4e37-b43c-8ff688b5cf87)
### 2、如果图片没有“拍摄日期”，则添加“拍摄日期”
很多相册类软件好像都会读取这个“拍摄日期”，而我整理照片的时候发现，有些图片没有这个属性，所以希望可在修改时一并添加
![Snipaste_2023-09-15_00-02-38](https://github.com/Cryolitia/PhotoTimeFix/assets/84775360/2f317721-22d2-42b1-9dfb-34c05b13315a)

**Comment by Cryolitia** [comment]
@henji-henji 你怎么把我要写的功能提前说出来了，不过最近太久没碰这个项目了，甚至主力机都换Linux了，可能需要一定时间复健

**Comment by henji-henji** [comment]
> @henji-henji 你怎么把我要写的功能提前说出来了，不过最近太久没碰这个项目了，甚至主力机都换Linux了，可能需要一定时间复健

哈哈哈哈哈，期待一下😀
另外可不可以把操作失败的文件，转移到同目录下的一个文件夹里，感觉这样会方便很多

**Comment by Cryolitia** [comment]
@henji-henji 操作失败的单独转移出来么…我可能会更接受另一个issue里面提到的，导出日志这个方案

**Comment by henji-henji** [comment]
@Cryolitia 我是想着单独转移出来可能更好处理，如果一堆文件中只有那么几个失败了的话，看着日志去找可能会有点麻烦

**Comment by henji-henji** [comment]
> @henji-henji 操作失败的单独转移出来么…我可能会更接受另一个issue里面提到的，导出日志这个方案

我是想着单独转移出来可能更好处理，如果一堆文件中只有那么几个失败了的话，看着日志去找可能会有点麻烦

**Comment by Cryolitia** [comment]
https://github.com/Cryolitia/PhotoTimeFix/commit/3446eed1890aa817edf7e79680e678fec09bab06
