### ISSUE TITLE
多张修复时 卡死

### ISSUE THREAD

**Issue by lhl900820** [Cryolitia/PhotoTimeFix#6]
几W张的时间  卡死没有反应看不到是否修复成功
可以分批修复吗

**Comment by Cryolitia** [comment]
我没几万张图片的测试环境……你是几万张在一个文件夹里面吗

**Comment by Cryolitia** [comment]
fix in https://github.com/Cryolitia/PhotoTimeFix/commit/9393e3c32c11150456297ec44a01f5dfcb93fd3d
