### ISSUE TITLE
1.照片多了后 进度条卡死不动， 2.卡无法通过查看日志记录TXT文件去判断是否依然在工作 或者失败文件列表。

### ISSUE THREAD

**Issue by xinyu532** [Cryolitia/PhotoTimeFix#7]
1.照片多了后 进度条卡死不动， 2.卡无法通过查看日志记录TXT文件去判断是否依然在工作 或者失败文件列表。
怎么才能够联系您，哪里可以下载最新版本。

**Comment by Cryolitia** [comment]
@xinyu532 新版本我还没发呢，联系我的话，telegram: https://t.me/NeuronDevelop

**Comment by Jetzow527** [comment]
同样的问题，文件夹里照片多了之后会卡死掉。

**Comment by Cryolitia** [comment]
https://github.com/Cryolitia/PhotoTimeFix/commit/67fbb86a32d6a6cd00f1938abd2a1f07063d8216

添加了日志文件记录、

卡死的问题主要是，我没有几万张图片的测试环境来复现

**Comment by Cryolitia** [comment]
> 1.照片多了后 进度条卡死不动，

fix in https://github.com/Cryolitia/PhotoTimeFix/commit/9393e3c32c11150456297ec44a01f5dfcb93fd3d
